#!/bin/bash
#
# Script to get active servers filtered by list of names.
#
# Example: ./a sirplease aurora
# 
# Author: Luckylock

names=""

for arg in "$@" 
do
    names="$names -n '$arg' "
done

eval "python3 steamGameServer_A2S_INFO.py -a $names < compList"
