#!/bin/bash
#
# Script to get active servers with part of arg1 in the info.
#
# Example: ./a chi
# 
# Author: Luckylock

python3 steamGameServer_A2S_INFO.py a < iplist | grep -i -e "$1" -e "Total" -B 1 -A 2
