#!/bin/bash
#
# Script to get active servers with arg1 in the name.
#
# Example: ./a chi
# 
# Author: Luckylock

python3 steamGameServer_A2S_INFO.py ap < iplist 2> failedConnections | grep -i -e "Name.*$1" -e "Total players" -B 0 -A 5
