#!/bin/bash
#
# Utility script to grab the consistently failing (or consistently successful) connections
#
# Author: Luckylock

for i in {1..100}:
do
    #./steamGameServer_A2S_INFO.py < connections &
    ./steamGameServer_A2S_INFO.py < failedConnections &
    wait
done
