#!/bin/bash
#
# Script to get active servers filtered by list of names.
#
# Example: ./a sirplease aurora
# 
# Author: Luckylock

names=""

for arg in "$@" 
do
    names="$names -n '$arg' "
done

eval "python3 a2sInfoPlayer.py -c 80 -a $names < serverlist/compList"
