#!/bin/bash
#
# Script to get empty servers filtered by list of names.
#
# Example: ./e chi
# 
# Author: Luckylock

names=""

for arg in "$@"
do
    names="$names -n $arg"
done

eval "python3 a2sInfoPlayer.py -c 80 -e $names < serverlist/compList"
