#!/bin/bash
#
# Script to search for a list of players in all the servers.
#
# Example: ./p lucky bob
# 
# Author: Luckylock

names=""

for arg in "$@"
do
    names="$names -p $arg"
done

eval "python3 a2sInfoPlayer.py -sa $names < serverlist/compList"
